name: QA Sphere Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Allows manual triggering

env:
  PLAYWRIGHT_VERSION: "1.51.1"

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-results
          path: junit-results/
          retention-days: 7
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  upload-to-qasphere:
    name: Upload Results to QA Sphere
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
      - name: Download test results
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: junit-results
          path: junit-results/
      
      - name: Setup Node.js
        if: always()
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install QAS CLI
        if: always()
        run: npm install -g qas-cli
      
      - name: Upload to QA Sphere
        if: always()
        env:
          QAS_TOKEN: ${{ secrets.QAS_TOKEN }}
          QAS_URL: ${{ secrets.QAS_URL }}
        run: qasphere junit-upload ./junit-results/results.xml
      
      - name: Summary
        if: always()
        run: echo "✅ Test results uploaded to QA Sphere successfully"